language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
after_script:
- ls
- cp ./build/index.html ./build/200.html
deploy:
  provider: surge
  skip_cleanup: true
  domain: people-counting-dashboard.surge.sh
  project: ./build/
on:
  branch: master